In [1]:
%load_ext autoreload
%autoreload 2

from matplotlib.pyplot import imshow
import matplotlib.pyplot as plt

%matplotlib inline
import numpy as np
import sys
sys.path.append('../')
import gp

/home/d/miniconda2/envs/NP/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Using gpu device 0: GeForce GTX TITAN (CNMeM is disabled, CuDNN 4007)
/home/d/miniconda2/envs/NP/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")


In [5]:
e_p = []
p = []

In [3]:
import cPickle as pickle
with open('../nets/IPMLB_FULL.p', 'rb') as f:
    cnn = pickle.load(f)
cnn.uuid = 'IPMLB'

KeyboardInterrupt: (KeyboardInterrupt(), <function _constructor_Function at 0x7f59b8e81848>, (<theano.compile.function_module.FunctionMaker object at 0x7f596e55f050>, [<None>, <None>, <CudaNdarray([[[[ 0.83101124 -0.45216268 -0.92241758]
   [ 0.44926044 -0.79137021 -0.85471934]
   [ 0.62316829 -0.22166604 -0.5351423 ]]

  [[ 0.74415201  0.76112461  0.14936428]
   [ 1.26601923  1.12129915  0.54457217]
   [ 0.73289531  0.6029588   0.08996633]]

  [[-0.20223477 -0.05420067 -0.5176177 ]
   [-0.16366521  0.24429148  0.12103456]
   [ 0.43135822  0.11404235  0.20076309]]

  [[ 0.01085452 -0.14073524  0.35528407]
   [ 0.1014398  -0.21538898 -0.13963255]
   [-0.17260572  0.19859107  0.22175764]]]


 [[[-0.42160168 -0.33796558 -0.10554801]
   [-0.55112571 -0.89287311 -0.78223509]
   [-0.5099296  -0.8778429  -1.06378591]]

  [[-0.62700075 -0.55552375 -0.26756749]
   [-0.1141824  -0.10648482 -0.13077492]
   [ 0.03338762  0.01803556  0.15733203]]

  [[-0.28123182  0.08279371  0.06133154]
   [-0.26863402 -0.42603293  0.01725472]
   [ 0.3666476  -0.98386133 -0.54569435]]

  [[-0.13484271 -0.26526099  0.2911244 ]
   [ 0.42529172  0.04707859 -0.48821592]
   [ 0.33630458  0.67504847  0.016005  ]]]


 [[[ 1.25536573  1.61147332  1.61617768]
   [-0.24261695  0.25609356  0.25410226]
   [-1.48116505 -1.34126687 -0.99922913]]

  [[ 0.44626012  0.21863577  0.56172657]
   [-0.30303037 -0.54896152 -0.37504318]
   [-0.06397472 -0.29694691 -0.4180465 ]]

  [[-0.47834331 -0.21126686  0.49019   ]
   [-0.84692895  0.37767103  0.10543503]
   [-0.61730427  0.64444244  0.62144709]]

  [[ 0.05778688  0.1833781  -0.08520789]
   [ 0.57905042  0.06180374  0.47970474]
   [ 0.34884197 -0.1029463   0.36515298]]]


 ..., 
 [[[-0.07212126  0.41497627  0.32952008]
   [ 0.04437019  0.89016879  0.54262209]
   [-0.09697887  0.26709726 -0.0759009 ]]

  [[-0.34860247 -0.3188796  -0.0791292 ]
   [-0.20706786 -0.51325405 -0.45413423]
   [ 0.49233451  0.18315828 -0.11095257]]

  [[ 0.30043569  0.13640419 -0.07883039]
   [ 0.09435701 -0.06755543 -0.10842759]
   [-0.22471718  0.11327182  0.12290932]]

  [[ 0.85377574  0.54417753  0.2029732 ]
   [-0.3245388  -0.04117646  0.41804892]
   [ 0.45198494  0.05717055  0.64358526]]]


 [[[ 0.27808616 -0.05840755 -0.99811262]
   [ 0.91650122  0.59587646 -0.42878583]
   [ 1.38801038  0.84957308 -0.27346233]]

  [[-0.30557671  0.67243505  1.05331039]
   [-0.75939018  0.08055729  0.8877579 ]
   [-0.99525791 -0.68197203  0.3973839 ]]

  [[-0.46158257  0.79644388  0.22149633]
   [-1.11750543 -0.05984045 -0.88105267]
   [ 1.00280964  0.97050434  0.44936067]]

  [[ 0.03072515  0.42680386 -0.50137824]
   [-0.43645719 -0.27598628 -0.25353488]
   [ 0.73373896 -0.48743752  0.14143114]]]


 [[[-0.29113311 -0.2968657  -0.76124632]
   [-0.41352701 -0.20361485 -0.76195771]
   [-0.37231886 -0.47130078 -0.59065205]]

  [[-0.4317973  -0.30489215 -0.16632286]
   [ 0.19728214  0.07837477  0.30107018]
   [ 0.47553018  0.43354931  0.45248222]]

  [[-0.19242385 -0.02724457  0.59242481]
   [-0.08976278 -0.04668926 -0.17313901]
   [-0.51755637 -0.39758518 -0.17454609]]

  [[ 0.24901141 -0.17936386 -0.91408461]
   [ 0.25167441 -0.33444363  0.00344374]
   [ 0.02630736  0.04460052 -0.24195156]]]])>, <CudaNdarray([-2.74057388 -1.13451767 -0.69347119 -0.65855223 -1.45420063 -1.3963747
 -2.58478141 -0.86258739 -1.56950152 -2.0154295  -0.83600777 -1.19224346
 -1.30910766 -1.30014694 -1.0975548  -1.19868994 -1.06602192 -1.18646228
 -0.86395139 -1.08066916 -1.09416664 -1.34036589 -0.67637753 -1.17393482
 -1.296646   -1.93042874 -2.02995753 -1.09843004 -0.55103594 -3.11809063
 -2.84745932 -1.39242232 -1.19986606 -0.82428789 -1.02349043 -6.47628355
 -1.57731855 -1.24140286 -1.23123968 -2.36973405 -3.52481961 -1.45581758
 -3.06090808 -0.98896873 -0.66302234 -1.20765138 -0.81468683 -1.02941835
 -2.59137821 -1.0085454  -1.76855326 -1.561041   -2.17170954 -0.9072175
 -1.88578737 -1.28662634 -1.43275952 -0.84804511 -1.40974557 -1.03664601
 -3.44133472 -0.92853475 -1.34622431 -1.69780052])>, <CudaNdarray([[[[ -1.03899086e+00  -7.07712948e-01  -2.11633012e-01]
   [ -7.01015055e-01  -5.49534857e-01  -4.23155546e-01]
   [ -4.74046022e-01  -6.90073490e-01  -3.20720673e-01]]

  [[ -2.84042004e-02   7.65760913e-02   1.68639973e-01]
   [  1.55218923e-02  -5.14774360e-02   1.02452047e-01]
   [ -1.79808512e-01   1.20908879e-02   1.63017139e-01]]

  [[  3.20427001e-01   1.84102327e-01  -7.90930837e-02]
   [ -9.83949155e-02  -7.94056952e-02   4.98850755e-02]
   [  8.11649710e-02  -3.69171977e-01   1.64390311e-01]]

  ..., 
  [[ -8.31661522e-02   3.43939334e-01  -7.62134641e-02]
   [ -1.26789913e-01   7.70685002e-02   1.37099728e-01]
   [ -2.34002825e-02  -7.41033182e-02  -4.06539366e-02]]

  [[  8.17659050e-02   3.09216175e-02   2.24263132e-01]
   [  1.50205746e-01  -1.83322132e-01   2.37460360e-02]
   [  9.91108567e-02   4.93976139e-02  -2.59389788e-01]]

  [[  9.94211063e-02  -1.39090121e-01   1.03914693e-01]
   [ -3.89624611e-02  -2.44604453e-01   1.40192807e-01]
   [ -1.02255931e-02  -1.08521447e-01  -5.45864552e-02]]]


 [[[  4.21363451e-02   7.60455206e-02   1.19353160e-02]
   [ -1.50640711e-01  -7.61038065e-02  -1.64500862e-01]
   [  6.96105585e-02   3.58057097e-02  -1.05892017e-01]]

  [[ -1.19794691e-02   2.35678688e-01   1.49746716e-01]
   [  2.74288267e-01   2.95506585e-02  -1.46746516e-01]
   [  7.02063292e-02   3.00397605e-01   1.46357521e-01]]

  [[ -3.98736686e-01   2.06390262e-01   2.11049512e-01]
   [ -8.29093456e-01   1.48714751e-01   5.05870223e-01]
   [ -5.65862775e-01  -8.11843053e-02   2.73979813e-01]]

  ..., 
  [[ -4.22204465e-01   1.69449568e-01   1.24200471e-01]
   [ -5.13087332e-01   2.71862149e-01   3.49688709e-01]
   [ -1.83554769e-01  -5.20480871e-02   4.14058179e-01]]

  [[  3.76208633e-01  -6.76626060e-03  -3.06220949e-01]
   [ -4.46010828e-02  -1.21677458e-01  -4.18908074e-02]
   [  6.00888073e-01   1.66827142e-01   7.95492157e-02]]

  [[  1.36160493e-01  -8.85431131e-04   4.21947725e-02]
   [  3.74704786e-02  -1.75046399e-01  -2.46715266e-02]
   [  1.28607646e-01   2.69978374e-01  -2.22416520e-02]]]


 [[[ -1.63706779e-01  -1.04198553e-01   4.06934679e-01]
   [ -2.32984364e-01  -2.72022456e-01  -5.58180586e-02]
   [ -8.14285278e-02  -3.11620295e-01   7.78380409e-02]]

  [[ -2.08281472e-01  -1.94994330e-01   1.93768099e-01]
   [  2.05065727e-01  -1.88912004e-01   1.02051280e-01]
   [  3.07391167e-01   1.94093883e-01   1.26985222e-01]]

  [[  2.89210826e-02   3.37665603e-02  -1.68885067e-01]
   [ -5.79501130e-02  -1.25212729e-01   1.82374328e-01]
   [ -6.30563498e-02  -6.66023344e-02   3.38032961e-01]]

  ..., 
  [[ -2.78496947e-02  -1.38177171e-01   1.40720326e-02]
   [ -7.05079958e-02   1.66841540e-02   1.32828847e-01]
   [ -2.38252133e-01  -9.54170898e-03  -1.29620969e-01]]

  [[ -8.87866020e-02   1.74003541e-01   1.28994912e-01]
   [ -8.15632716e-02   9.21947360e-02  -1.27922624e-01]
   [ -1.75515562e-01  -4.23329696e-02  -8.66991132e-02]]

  [[  8.89702663e-02   2.65070163e-02   1.22281060e-01]
   [  2.14318112e-02   1.01329006e-01   1.04073621e-01]
   [  1.26187846e-01   7.41014481e-02  -4.58548576e-01]]]


 ..., 
 [[[ -1.39322085e-02  -7.48385116e-02   6.04572594e-02]
   [  7.21339732e-02  -1.04897290e-01   1.32871062e-01]
   [ -1.42650649e-01   4.01423126e-02   1.33083910e-01]]

  [[  1.29407048e-01  -1.76004156e-01  -1.76393196e-01]
   [ -4.27057594e-01  -2.73238778e-01  -4.65516970e-02]
   [  4.92012538e-02   1.88883349e-01  -2.40974035e-02]]

  [[  2.82483578e-01  -3.83545682e-02  -5.32374501e-01]
   [  1.31620318e-01   4.44245517e-01  -4.54534031e-02]
   [ -6.72854900e-01   1.17982086e-02  -3.06252902e-03]]

  ..., 
  [[  1.17148787e-01  -7.57174045e-02  -1.62829623e-01]
   [ -7.18301907e-02  -2.06233054e-01  -2.17311889e-01]
   [  1.88488483e-01  -1.97878256e-01  -3.31659973e-01]]

  [[  6.57003224e-02   2.45777845e-01  -5.15913218e-02]
   [ -1.59431592e-01  -1.47671178e-01  -1.94173589e-01]
   [ -1.86218843e-01  -5.02392888e-01  -3.60086113e-01]]

  [[ -3.82547788e-02  -2.11749300e-01  -1.62553191e-01]
   [ -2.23683923e-01  -2.77007937e-01  -3.30271095e-01]
   [ -3.59805077e-01  -1.29774302e-01  -2.24200502e-01]]]


 [[[  9.00591910e-02   1.53719157e-01   1.29912362e-01]
   [ -5.41887999e-01  -1.40945524e-01   1.78245559e-01]
   [ -3.90058637e-01   2.38208249e-01   1.45306677e-01]]

  [[ -3.24758232e-01  -1.03807926e-01   2.88663805e-01]
   [ -9.80183482e-02  -1.49351090e-01  -4.64355834e-02]
   [ -8.06551948e-02  -2.21072212e-01   5.96008636e-02]]

  [[  1.18570644e-02  -2.07448438e-01  -4.14732426e-01]
   [  6.32610396e-02   5.97655308e-03  -1.29465088e-01]
   [ -4.93409038e-02  -3.84661071e-02  -3.48135084e-01]]

  ..., 
  [[ -1.66930556e-01  -5.26171438e-02  -1.01584740e-01]
   [ -4.51719351e-02  -4.13630866e-02  -3.04748062e-02]
   [ -1.03941984e-01  -2.04513341e-01  -2.35877708e-01]]

  [[  6.17120927e-03  -6.78258240e-02   2.99164802e-01]
   [ -3.42159241e-01  -1.02156721e-01  -1.23017870e-01]
   [ -2.23340355e-02  -1.97053552e-01   1.80716872e-01]]

  [[ -5.04926920e-01  -5.51133215e-01  -2.16891497e-01]
   [ -1.67067677e-01  -7.70940706e-02  -1.65254682e-01]
   [  5.47637604e-02   8.38366896e-02   3.49199682e-01]]]


 [[[ -2.00566560e-01  -6.08267859e-02   2.56233215e-01]
   [ -2.05440164e-01   3.46872099e-02  -1.73426680e-02]
   [ -2.32734665e-01  -8.38465095e-02   2.78081506e-01]]

  [[ -5.78814298e-02  -2.83751756e-01  -4.31368828e-01]
   [ -1.08790912e-01  -3.21476273e-02  -5.50257117e-02]
   [ -1.51891857e-01   8.87714326e-02   3.36857200e-01]]

  [[ -5.11330813e-02  -2.88898975e-01  -2.21825927e-01]
   [ -2.15393394e-01  -3.02071840e-01  -2.43661910e-01]
   [ -4.31054048e-02  -1.30863607e-01  -2.44210571e-01]]

  ..., 
  [[ -4.46269572e-01  -2.99920291e-01  -2.03506961e-01]
   [ -2.17233911e-01  -2.26960093e-01  -1.80521339e-01]
   [ -4.70269352e-01  -3.12532425e-01  -2.79511690e-01]]

  [[  2.18881071e-01   2.63184309e-01  -2.04858646e-01]
   [ -1.06189549e-01   1.81126595e-01   1.26284093e-01]
   [ -4.75525707e-01  -7.02133253e-02  -3.45842876e-02]]

  [[ -4.19395655e-01  -2.08264068e-01   6.50537238e-02]
   [ -3.91429096e-01  -3.48257005e-01  -1.41326636e-01]
   [ -1.17312081e-01   2.40765121e-02   2.72505522e-01]]]])>, <CudaNdarray([ 0.49784726 -2.71426821 -1.11221349 -1.1041913  -1.03609371 -3.04800701
 -0.16594319 -0.03479904 -0.47234794  0.45210433  0.56915796 -0.26683602
  0.07859489 -0.26729497 -0.98864454 -0.10822032  0.33516884  0.06537934
  0.82912201 -1.07308316 -1.50282371 -0.41145244  0.26148129 -0.74645901
  0.89112067  0.20490104 -0.4848544   0.46606058 -1.0468235  -0.63714308
 -2.02621412  1.12329006  0.5200491  -0.40593448 -0.35442084 -0.69448453
 -0.23921628 -0.1935934  -1.32455301 -0.05105822 -0.77319735 -1.08783245
 -0.51363599 -1.1831547   1.16395259  0.53548926  0.0685631   0.10538217])>, <CudaNdarray([[[[ -5.55648625e-01  -1.79825678e-01  -3.61613005e-01]
   [ -3.55482250e-01   8.51372853e-02   1.08920790e-01]
   [ -2.03540817e-01  -3.66130799e-01  -2.58501291e-01]]

  [[  2.71673519e-02  -9.07710791e-02  -9.26804915e-02]
   [ -1.43091112e-01   9.90352780e-02  -3.21438052e-02]
   [  2.56391056e-03  -2.15093404e-01  -2.71666080e-01]]

  [[ -2.85745054e-01  -2.53985852e-01  -1.43779561e-01]
   [ -1.89220712e-01  -4.57067430e-01  -2.80681461e-01]
   [ -2.18005657e-01  -2.31698230e-01  -1.33097291e-01]]

  ..., 
  [[  1.95007294e-01   5.20254485e-02  -5.75287491e-02]
   [ -1.11263946e-01  -7.18951523e-02   2.05041841e-01]
   [  2.87175179e-01   1.32054985e-01   2.63389111e-01]]

  [[ -3.36218834e-01  -1.06769353e-01  -6.85672522e-01]
   [ -3.97022426e-01  -9.36661102e-03  -3.61389220e-01]
   [  2.45367482e-01   2.15815440e-01  -6.20777346e-02]]

  [[ -9.23185110e-01  -5.76843917e-01   1.17314950e-01]
   [ -4.69182074e-01   3.14978659e-02  -1.13426581e-01]
   [ -4.43677783e-01   8.15381780e-02   2.19053328e-01]]]


 [[[ -7.32762039e-01  -5.15851140e-01  -5.43630481e-01]
   [ -3.93457144e-01   1.55082449e-01  -1.61027566e-01]
   [ -3.76486599e-01   4.75623518e-01  -9.33504552e-02]]

  [[ -1.29457727e-01  -3.79549444e-01  -8.00150558e-02]
   [  4.34240676e-04  -2.54949749e-01   5.27031571e-02]
   [  2.57813781e-01  -1.70749292e-01  -1.76687278e-02]]

  [[  1.67016372e-01   1.20158710e-01   4.85534035e-03]
   [ -1.35218903e-01  -7.44681293e-03  -6.91842288e-02]
   [ -2.59279370e-01  -4.27595258e-01   6.71064481e-02]]

  ..., 
  [[  1.67320609e-01  -2.90186316e-01   7.30859935e-02]
   [  1.17270239e-01  -1.27158880e-01  -2.77034054e-03]
   [  2.04600364e-01  -1.17118977e-01   8.35249797e-02]]

  [[ -3.35401028e-01  -2.67125934e-01  -2.52650708e-01]
   [ -6.80978000e-01  -3.42269927e-01  -5.07875681e-01]
   [ -7.73451865e-01  -2.19997376e-01  -6.53473318e-01]]

  [[ -3.47463638e-01   2.69559950e-01  -3.42725992e-01]
   [ -6.57833755e-01  -8.37404504e-02  -2.46688366e-01]
   [ -6.52560771e-01  -2.26491943e-01  -3.70176256e-01]]]


 [[[ -3.18797588e-01  -4.92443740e-01  -6.24714315e-01]
   [ -1.52522502e-02  -4.83457744e-01  -5.77130973e-01]
   [  2.79248774e-01  -1.31189093e-01  -2.44657531e-01]]

  [[ -3.72677088e-01  -2.06303030e-01  -2.56270654e-02]
   [ -1.94880158e-01  -6.13101661e-01  -6.74544871e-01]
   [ -5.14626922e-03  -2.40905657e-01  -2.96184480e-01]]

  [[  1.44294932e-01   5.49624227e-02   4.96466495e-02]
   [  1.61056442e-03  -1.01255044e-01  -1.84084326e-01]
   [ -2.01997414e-01   7.14274123e-02  -3.36322844e-01]]

  ..., 
  [[ -1.14907198e-01  -1.89924881e-01   7.52249286e-02]
   [ -2.07206875e-01  -4.47041579e-02  -5.60476482e-02]
   [  3.68176936e-03   2.91991308e-02  -1.59765221e-02]]

  [[ -3.28368038e-01  -3.28406155e-01  -8.09243545e-02]
   [  1.07602224e-01  -3.48054320e-01  -3.20792437e-01]
   [ -4.36068267e-01  -2.93477982e-01  -6.80678114e-02]]

  [[  6.44836128e-02  -1.38979301e-01   1.70734048e-01]
   [ -8.25592577e-02  -6.52305305e-01  -9.03024524e-02]
   [ -7.15177834e-01  -2.36048579e-01  -9.93438363e-02]]]


 ..., 
 [[[ -5.74441515e-02  -2.01479761e-05   3.64914209e-01]
   [ -1.20179340e-01  -2.06076000e-02   3.53526771e-01]
   [  4.84761670e-02  -1.22195743e-01  -2.87635505e-01]]

  [[  9.54280570e-02   6.21371418e-02  -1.10822320e-01]
   [  6.61599040e-02  -5.66540301e-01  -6.54143393e-01]
   [ -4.25048470e-01  -3.97795856e-01  -1.98025033e-01]]

  [[ -3.49553376e-02  -2.05245353e-02  -3.19508523e-01]
   [  6.76648095e-02  -1.02825813e-01   8.62115920e-02]
   [  1.72031745e-01  -2.79542357e-01   3.32226530e-02]]

  ..., 
  [[ -2.83571124e-01  -3.86120863e-02  -1.01143934e-01]
   [ -1.17121726e-01  -3.41369808e-01  -1.97162181e-02]
   [ -1.54332444e-01  -8.29130769e-01  -3.63507330e-01]]

  [[  7.55020045e-03  -1.96728647e-01   1.23352945e-01]
   [  1.60791352e-02  -4.00688648e-01  -2.30615109e-01]
   [  3.36848572e-02  -3.52880061e-01  -1.70150161e-01]]

  [[ -8.41762245e-01  -4.68672127e-01  -4.92002100e-01]
   [ -3.25839847e-01   2.50189006e-02  -1.25648424e-01]
   [  2.09391847e-01  -1.88512038e-02  -3.06263715e-01]]]


 [[[ -6.10930383e-01  -7.88463652e-02   2.31257789e-02]
   [ -6.32044077e-01  -3.72007973e-02   2.14581832e-01]
   [ -1.72792822e-02   2.34253228e-01   7.00529873e-01]]

  [[ -3.79397690e-01  -1.84121013e-01  -1.14102766e-01]
   [ -3.86830062e-01  -1.13217428e-01  -1.84172884e-01]
   [ -4.34637666e-01  -5.04779875e-01  -3.54876012e-01]]

  [[ -2.88205981e-01  -2.99837394e-03  -1.09929599e-01]
   [ -4.10349607e-01  -2.09614977e-01  -1.08842507e-01]
   [ -3.54432195e-01  -4.73019272e-01   1.63771957e-02]]

  ..., 
  [[  2.34551474e-01  -2.03053206e-01  -4.90765721e-01]
   [  3.31355453e-01  -1.16921186e-01  -3.58813375e-01]
   [ -6.03953362e-01  -5.66076398e-01  -1.68049440e-01]]

  [[ -3.97382945e-01  -2.11691439e-01  -2.14038100e-02]
   [ -1.35982051e-01  -6.51247725e-02  -2.08420947e-01]
   [  2.09441975e-01   1.81963041e-01   5.11703230e-02]]

  [[ -5.55412710e-01  -1.58026785e-01   6.41783774e-02]
   [ -1.61994115e-01  -2.32920408e-01  -8.03103149e-02]
   [  6.35767728e-02   4.21562716e-02  -1.70794874e-01]]]


 [[[  4.00789320e-01   2.27411151e-01   7.76451686e-03]
   [  1.55687809e-01   1.80896848e-01  -2.00919002e-01]
   [  1.53829113e-01  -9.89933386e-02  -1.18696764e-01]]

  [[ -5.42708874e-01  -6.07862249e-02   6.17021136e-02]
   [ -4.89879906e-01  -3.65410596e-01   5.69286346e-02]
   [ -1.97755307e-01  -6.64011896e-01  -1.62389532e-01]]

  [[ -2.22932771e-02  -1.78043172e-01  -1.84667036e-01]
   [ -1.84764639e-01  -1.50077954e-01  -4.66146648e-01]
   [ -2.75428861e-01   1.26808599e-01  -4.86701965e-01]]

  ..., 
  [[ -1.67878807e-01  -2.43076250e-01  -2.25258723e-01]
   [  1.18252508e-01   1.55508265e-01  -4.16026115e-02]
   [  1.90830737e-01   1.06237851e-01   3.38129640e-01]]

  [[ -1.70554057e-01  -4.82548401e-02  -7.61807486e-02]
   [  1.18868969e-01   1.78441152e-01  -6.30484894e-02]
   [  2.24672869e-01   3.60591292e-01   2.36986890e-01]]

  [[ -1.92939460e-01   1.24149211e-01  -2.29781792e-01]
   [ -1.96496978e-01  -4.17728722e-03   2.77659327e-01]
   [  7.15690106e-02   3.53786737e-01   3.25949788e-01]]]])>, <CudaNdarray([  1.27055705e+00   8.50887418e-01   8.89142096e-01   7.73467600e-01
  -3.52138281e-02  -9.31092322e-01   1.00548851e+00  -1.20622742e+00
  -8.93839419e-01  -1.32000232e+00  -1.12079298e+00   1.14844131e+00
  -1.64053068e-01  -5.01149833e-01  -1.36425510e-01  -1.37293428e-01
  -9.11656320e-01  -1.89826548e+00   1.11320841e+00  -1.03427899e+00
  -5.03704846e-01  -6.12142324e-01  -5.65057576e-01  -1.83385730e-01
   4.46549058e-02  -4.87145096e-01   1.28062832e+00  -6.26982450e-01
  -1.63078332e+00   3.12236361e-02   6.24971390e-01  -1.69142187e-01
  -1.15813471e-01  -3.72082412e-01  -2.00406820e-01  -1.43870770e-03
   3.26791376e-01  -1.08686164e-01   2.23068029e-01  -1.23560476e+00
  -9.62841436e-02   3.15122992e-01   6.04475856e-01  -7.70970881e-01
   6.31489813e-01  -3.87436181e-01   4.27955955e-01   1.13671340e-01])>, <CudaNdarray([[[[ 0.20699319  0.2013782   0.26907879]
   [-0.58195883 -0.38540438 -0.07240457]
   [-0.16374162 -0.11952751 -0.23488639]]

  [[-0.31098777 -0.28300887 -0.35616425]
   [-0.34404886 -0.37568954 -0.24432164]
   [-0.592906   -0.8672151  -0.4145757 ]]

  [[-0.54837143 -0.00803814  0.22543061]
   [-0.61656743 -0.0418414   0.11627364]
   [ 0.0073747  -0.11680636 -0.13924092]]

  ..., 
  [[ 0.15914346  0.03732125  0.15304466]
   [-0.25509763 -0.20628117 -0.19913357]
   [ 0.26758206 -0.03504071 -0.14913511]]

  [[ 0.12625043 -0.0114356  -0.04234314]
   [ 0.11181271 -0.00714431 -0.06726231]
   [-0.31914628 -0.09711426 -0.02451522]]

  [[ 0.18885413  0.05213578 -0.22542185]
   [ 0.20163171 -0.04044927 -0.08259725]
   [ 0.14037065 -0.31893805 -0.3056078 ]]]


 [[[ 0.10505183  0.0843349  -0.57331598]
   [ 0.04833136  0.0691833  -0.03750575]
   [ 0.04499397  0.1464811   0.22817394]]

  [[-0.05536383  0.09383938  0.12866049]
   [-0.16909552  0.04706055  0.03530479]
   [-0.23509692 -0.45561871  0.02804477]]

  [[-0.23888488  0.09540261  0.14374751]
   [ 0.1850135   0.17701079  0.08370428]
   [-0.17606618 -0.37336686  0.09134468]]

  ..., 
  [[ 0.02525026  0.1269418  -0.05586118]
   [ 0.02385484 -0.10042107  0.1017136 ]
   [-0.10112617 -0.16565005  0.07036643]]

  [[ 0.04418899  0.134166   -0.36088249]
   [-0.06577702  0.20694712 -0.38826266]
   [-0.3456482   0.33338091  0.19576673]]

  [[-0.6085431  -0.08657744 -0.51388979]
   [-0.12194053 -0.08553903 -0.46814999]
   [-0.47653204 -0.18545027 -0.21915966]]]


 [[[-0.02281508  0.12503664 -0.28227508]
   [-0.17915194 -0.36990798 -0.05005167]
   [-0.02025367 -0.05584679  0.0166137 ]]

  [[-0.33090734 -0.47326595  0.0383277 ]
   [ 0.20293297 -0.28655279 -0.05095611]
   [ 0.09031997 -0.05666732 -0.10507414]]

  [[-0.29664114 -0.53470111  0.10287395]
   [-0.04709946 -0.14990729  0.0778084 ]
   [ 0.35083401  0.07387653 -0.05328261]]

  ..., 
  [[-0.51846009 -0.236835   -0.22659963]
   [-0.50640941 -0.53435594 -0.16856329]
   [-0.04450612 -0.06036286 -0.0104828 ]]

  [[-0.1515477  -0.12912974 -0.56418335]
   [ 0.29304543 -0.10884951  0.0070933 ]
   [ 0.34004366  0.27846581  0.14274275]]

  [[-0.27796367  0.14167489 -0.31374326]
   [-0.16969347 -0.13885014 -0.18226485]
   [-0.27951482 -0.00992526  0.07558949]]]


 ..., 
 [[[-0.23150547 -0.32728028 -0.25769648]
   [-0.17655089 -0.41131529  0.05343656]
   [-0.18227644 -0.17692231  0.00838388]]

  [[ 0.02864032  0.14321266  0.12594509]
   [-0.27837056 -0.05131846  0.10145558]
   [-0.50749558 -0.10084471 -0.03569219]]

  [[-0.03847692 -0.58925426 -0.77645123]
   [ 0.22065689  0.00345068 -0.14500436]
   [ 0.24153152  0.10567209 -0.39263681]]

  ..., 
  [[-0.01037799 -0.01221335  0.04547688]
   [ 0.06419542 -0.01942509  0.20392558]
   [-0.03578002  0.24260777  0.19972987]]

  [[-0.07895266  0.19871186  0.05674917]
   [ 0.06790239 -0.0385462  -0.24463423]
   [ 0.01233307 -0.45919096 -0.24354298]]

  [[ 0.19116873  0.09023892  0.08200169]
   [-0.27167848 -0.07721376 -0.13123474]
   [ 0.2535713   0.14867975 -0.23826264]]]


 [[[ 0.19106571  0.02854091  0.06139765]
   [ 0.30297297  0.14660056 -0.07580548]
   [ 0.21287966 -0.08717956  0.26693073]]

  [[-0.55640596 -0.66656661 -0.66886538]
   [ 0.04251923 -0.4210366   0.19398862]
   [ 0.23728853  0.22951351  0.16600609]]

  [[ 0.25252715 -0.07036147 -0.01103672]
   [-0.01437161 -0.08905008 -0.15794489]
   [ 0.06510416 -0.20819385 -0.23607792]]

  ..., 
  [[-0.11612321  0.197984   -0.06423724]
   [ 0.04049082  0.20648503  0.23354927]
   [ 0.06491268 -0.11354759 -0.0466683 ]]

  [[ 0.0721854  -0.1971247  -0.02225072]
   [-0.32230574 -0.32425833  0.42623046]
   [-0.75231457 -0.25579238  0.28591195]]

  [[ 0.15298374  0.04932999  0.34639147]
   [ 0.17260227  0.03551251  0.05287162]
   [ 0.15045966 -0.17068471 -0.40324107]]]


 [[[-0.15075611  0.11353582  0.07292648]
   [-0.34331554 -0.06689552 -0.1733899 ]
   [-0.15645373 -0.31936792 -0.2078416 ]]

  [[-0.08005071 -0.13809991 -0.12880091]
   [ 0.06236064 -0.02503674 -0.43043342]
   [-0.31823993 -0.16109647 -0.5239132 ]]

  [[ 0.05150248 -0.12936625 -0.25815621]
   [ 0.24772477 -0.01911427 -0.35052732]
   [ 0.21586443  0.14792195  0.15761676]]

  ..., 
  [[ 0.01544535 -0.31117681  0.21648997]
   [-0.46108755 -0.34196696 -0.13508414]
   [-0.5066644  -0.05267448 -0.3300153 ]]

  [[-0.11529198 -0.00449779  0.21895851]
   [-0.09709139  0.04266135  0.15187022]
   [ 0.10297898  0.19023524  0.01521488]]

  [[ 0.08442704  0.33765978  0.47518468]
   [-0.08595871  0.1405237   0.03329588]
   [-0.49468771 -0.16239651  0.13497087]]]])>, <CudaNdarray([-0.85461867 -1.86372256 -1.83810806 -1.30129552 -2.25499082 -1.58926201
 -1.27909851  0.11986187 -0.01122112 -0.73687857 -1.83246195 -1.48389208
 -1.09200466 -1.08404684 -1.23793888 -1.06812596 -0.54343522 -2.68596625
 -1.90270388 -1.18021798 -3.15566039 -1.96465921 -0.09206514 -0.23439957
 -0.6171484  -0.03147016  0.64855653 -1.8581574  -0.5476042  -1.42260003
 -1.43420613 -2.69175601 -0.99124217 -0.68188941 -1.45070386  0.73159212
 -0.036773   -1.93029594 -2.2104187  -2.21118212 -1.13737571 -2.31913924
 -1.85402608 -0.16982625 -0.01069263  1.64269364 -0.73218721 -0.82166547])>, <CudaNdarray([[-0.06848672 -0.33572665 -0.07107727 ..., -0.17395231 -0.09427123
  -0.15778545]
 [-0.1053133  -0.12989189 -0.11146113 ..., -0.05436127 -0.04165371
  -0.05645037]
 [-0.07607694  0.1937665  -0.08325466 ..., -0.0128378  -0.06449713
  -0.07773026]
 ..., 
 [-0.08130579  0.08930684  0.0105402  ..., -0.12867884 -0.25652361
  -0.07186937]
 [ 0.07619429 -0.01234148  0.02239468 ..., -0.11565392 -0.07549141
  -0.1699619 ]
 [-0.0517144  -0.08033436 -0.1534216  ..., -0.16262934  0.04459566
  -0.01990528]])>, <CudaNdarray([ 0.52357852 -0.01783111  0.07731287 -0.00364406 -0.35613233 -0.32693422
 -0.12796393 -0.29243365 -0.31510758 -0.06928634  0.2329455  -0.11234906
 -0.35195634 -0.57962024 -0.23654303 -0.16352095 -0.17839967 -0.34639308
 -0.39088351 -0.07987365 -0.34626684 -0.01925754 -0.47046909  0.22863658
 -0.36188659 -0.24834223 -0.40385228 -0.46205595 -0.58263499 -0.30537841
  0.38482466 -0.15126875 -0.46604154 -0.3130644   0.02149743 -0.34848282
 -0.24013472 -0.40802357 -0.57288998 -0.14348722 -0.19219846 -0.2847088
 -0.41119453 -0.38899589 -0.53053039 -0.06887289  0.05662401 -0.2764014
 -0.4875572  -0.09845036 -0.34658757 -0.2734898  -0.36827528 -0.49329543
 -0.18831451 -0.43290284 -0.24036311 -0.3569319   0.26829717 -0.52199906
 -0.10858479 -0.36605829 -0.29521289 -0.41880953 -0.41492102 -0.33575931
 -0.48623294  0.3217217  -0.27030534 -0.32895422 -0.52415931  0.22506455
 -0.28238952 -0.5864594   0.52458072  0.10082451 -0.21772686 -0.19034253
  0.2589508   0.24633992 -0.35676482 -0.30276668 -0.13991085 -0.21367197
 -0.44213939 -0.31238797 -0.32260439 -0.28380531 -0.34743235 -0.39402589
  0.24449416 -0.34010997  0.39104825 -0.35936487 -0.28533751 -0.40035331
 -0.29501492 -0.38677913 -0.44412914  0.01422633 -0.3453556  -0.50576997
 -0.22333752 -0.16369551 -0.27767888 -0.18318087 -0.0877958  -0.13896893
 -0.13851462 -0.09876841 -0.32290983 -0.48627183 -0.00338196 -0.28516126
 -0.38968039 -0.49598476 -0.32379904 -0.14818592 -0.4638887   0.29184014
 -0.03173776 -0.43803906 -0.60893506 -0.26404229  0.06498861  0.13461599
 -0.00493341  0.39552459  0.17613403 -0.15922701  0.12015506 -0.11280567
 -0.44072449 -0.05592389  0.58828735 -0.38194701 -0.17959666 -0.29529426
 -0.39595687  0.02977487 -0.21576361 -0.07933643 -0.33692628 -0.41386136
 -0.50428945 -0.19546616 -0.35819575 -0.40301138  0.24154288 -0.31251034
 -0.28872401 -0.3779012  -0.39568758 -0.46067911 -0.45391703  0.38111824
 -0.27443603 -0.29580015  0.34471974 -0.38461193 -0.46627942 -0.37328067
  0.27390683 -0.25727731 -0.24887413 -0.19804481 -0.11404207  0.20817073
 -0.61621475 -0.34672672 -0.15061474 -0.2041375  -0.02946394 -0.09461129
 -0.2400448  -0.25069812 -0.2658585   0.39937869 -0.5702796  -0.27101833
 -0.0985413  -0.02901251 -0.33886659 -0.43808007 -0.25267333 -0.29406348
 -0.0107666  -0.30063695 -0.23241754 -0.04143662 -0.30632222 -0.44307354
 -0.32479161 -0.19375615 -0.08727518 -0.31011057 -0.41108403 -0.23616123
 -0.3806456  -0.37781402 -0.31396595 -0.03323183 -0.2826466  -0.55961293
  0.09723458  0.4324038  -0.4447602  -0.12822288 -0.33649722 -0.46298087
 -0.42106128  0.712493    0.22792031 -0.2211436  -0.2855351   0.13757761
 -0.2352581  -0.02834443 -0.57085526 -0.31747121 -0.27859983 -0.41983455
 -0.20311739  0.04826026 -0.23682971 -0.53673124 -0.47183874 -0.15817536
 -0.34489369 -0.3755281  -0.33744821 -0.03757681 -0.19875269 -0.32473496
 -0.19288358  0.24819569 -0.38563603 -0.45698711 -0.0822138  -0.50499064
 -0.31096229 -0.35365707 -0.06800243 -0.32865894 -0.22331034 -0.391332
  0.07080496  0.23248808  0.15689689 -0.39302257 -0.26074806  0.13585259
 -0.44453838 -0.30344915 -0.36679229 -0.13879441 -0.46136782 -0.20684598
  0.73663926 -0.64427888 -0.23848794  0.18872266 -0.26647669 -0.34564805
 -0.53769571 -0.28196073  0.1393282  -0.27473903 -0.38637713 -0.40029821
 -0.24811952  0.2693747  -0.40213484  0.0591583   0.27540344  0.17569894
 -0.22156411 -0.11748885  0.37776309 -0.32430854 -0.61923176 -0.40115964
  0.01748041 -0.36342731 -0.36302677  0.12329946 -0.47874576  0.14094758
 -0.51723963 -0.21139294 -0.08989806 -0.43624386 -0.19295749  0.35104665
 -0.47666857 -0.33413064  0.34239367 -0.34059665  0.76573247  0.3221353
 -0.34732318  0.23286167 -0.34926352 -0.14106604 -0.46457344  0.15495199
 -0.10631211 -0.3132982  -0.25006017 -0.54519612  0.25929168 -0.38716224
 -0.32241088 -0.07562296  0.5857175  -0.49681512 -0.58091128 -0.02452225
  0.34577787 -0.18901156 -0.43460339 -0.2374524  -0.32651827 -0.25215653
 -0.38206542 -0.14136426 -0.48309159 -0.40168726 -0.37955669 -0.13195479
 -0.24653247 -0.21106654 -0.26149884 -0.29968277 -0.14129052 -0.14729905
 -0.32032147 -0.21844411  0.19615367  0.39451849 -0.00794706 -0.22201607
 -0.28843975 -0.31325033 -0.27143949 -0.56251854 -0.38388371 -0.4103083
 -0.37241739 -0.34709114 -0.06099851 -0.41499519 -0.4108997   0.59748715
 -0.40587428 -0.18558121  0.0438692  -0.28604761 -0.32117033 -0.45882159
 -0.52975065 -0.39017385 -0.56362212  0.0820787   0.15889055 -0.44029233
 -0.31319505 -0.13850315  0.46378759 -0.43248558 -0.47536048 -0.20070918
 -0.22525129 -0.4666813  -0.18412945  0.30412441  0.32067299 -0.47067124
 -0.07593413 -0.32684657  0.06977993  0.21698521 -0.448668   -0.32665497
 -0.32957852  0.39889029  0.07412888 -0.30364683 -0.22588806 -0.20183824
 -0.4677639  -0.07294455 -0.17599098  0.10982081 -0.38466233 -0.14775789
 -0.03250871  0.48380649 -0.39447561  0.18687671  0.85304582 -0.30317995
 -0.15089183 -0.04337175 -0.25354233 -0.45101556  0.36320588  0.76642936
 -0.14543885 -0.37699264 -0.23424518  0.30583501  0.06192807 -0.40903655
 -0.29673663 -0.21148628  0.46016479  0.19370078 -0.35756475 -0.36428457
 -0.30110162 -0.30343154 -0.14009333 -0.30904722 -0.45453531 -0.24182095
 -0.43088859 -0.17942481 -0.48664209 -0.23568381 -0.1634589  -0.15664105
 -0.33569863 -0.35428596 -0.22757947 -0.29998881 -0.16339374 -0.31850693
 -0.40565157 -0.24922869 -0.2513068  -0.19725107 -0.58533931  0.10144134
 -0.39964196 -0.17208143 -0.48142383 -0.24599028 -0.09064478 -0.1574381
  0.09930992 -0.42003098 -0.12762159 -0.00608147  0.00643839 -0.50780487
  1.01192486 -0.01556108  0.0581543  -0.25012633 -0.4601917   0.22153559
 -0.24238002 -0.17479649 -0.34798312  0.08447235 -0.38560548 -0.31243512
 -0.58055836 -0.24480104 -0.40828323 -0.2001816  -0.28481776 -0.32080147
 -0.5565514   0.0268389  -0.1883125  -0.36878756  0.00168926 -0.27392891
 -0.2517961  -0.16945283 -0.26607943 -0.06422154 -0.07502812  0.01182062
 -0.21326819 -0.40349117 -0.47873637 -0.29913801 -0.18927744 -0.30986848
 -0.18622714 -0.0474378  -0.37858048  0.16422316 -0.02008451 -0.21538948
 -0.4574129   0.00652995 -0.1200077  -0.20264925 -0.15487912 -0.13973069
 -0.02296904 -0.27035806 -0.42095849 -0.3561379  -0.19328526 -0.0071193
 -0.53268999 -0.38141188])>, <CudaNdarray([[ 0.02255613 -0.02403588]
 [-0.10956398 -0.02643624]
 [ 0.01040248  0.05602583]
 ..., 
 [-0.09703961  0.09959773]
 [ 0.0451781  -0.08670858]
 [ 0.01042011 -0.07449926]])>, <CudaNdarray([-0.43991706  0.4402543 ])>], [None, None, CudaNdarray([[[[ 0.83101124 -0.45216268 -0.92241758]
   [ 0.44926044 -0.79137021 -0.85471934]
   [ 0.62316829 -0.22166604 -0.5351423 ]]

  [[ 0.74415201  0.76112461  0.14936428]
   [ 1.26601923  1.12129915  0.54457217]
   [ 0.73289531  0.6029588   0.08996633]]

  [[-0.20223477 -0.05420067 -0.5176177 ]
   [-0.16366521  0.24429148  0.12103456]
   [ 0.43135822  0.11404235  0.20076309]]

  [[ 0.01085452 -0.14073524  0.35528407]
   [ 0.1014398  -0.21538898 -0.13963255]
   [-0.17260572  0.19859107  0.22175764]]]


 [[[-0.42160168 -0.33796558 -0.10554801]
   [-0.55112571 -0.89287311 -0.78223509]
   [-0.5099296  -0.8778429  -1.06378591]]

  [[-0.62700075 -0.55552375 -0.26756749]
   [-0.1141824  -0.10648482 -0.13077492]
   [ 0.03338762  0.01803556  0.15733203]]

  [[-0.28123182  0.08279371  0.06133154]
   [-0.26863402 -0.42603293  0.01725472]
   [ 0.3666476  -0.98386133 -0.54569435]]

  [[-0.13484271 -0.26526099  0.2911244 ]
   [ 0.42529172  0.04707859 -0.48821592]
   [ 0.33630458  0.67504847  0.016005  ]]]


 [[[ 1.25536573  1.61147332  1.61617768]
   [-0.24261695  0.25609356  0.25410226]
   [-1.48116505 -1.34126687 -0.99922913]]

  [[ 0.44626012  0.21863577  0.56172657]
   [-0.30303037 -0.54896152 -0.37504318]
   [-0.06397472 -0.29694691 -0.4180465 ]]

  [[-0.47834331 -0.21126686  0.49019   ]
   [-0.84692895  0.37767103  0.10543503]
   [-0.61730427  0.64444244  0.62144709]]

  [[ 0.05778688  0.1833781  -0.08520789]
   [ 0.57905042  0.06180374  0.47970474]
   [ 0.34884197 -0.1029463   0.36515298]]]


 ..., 
 [[[-0.07212126  0.41497627  0.32952008]
   [ 0.04437019  0.89016879  0.54262209]
   [-0.09697887  0.26709726 -0.0759009 ]]

  [[-0.34860247 -0.3188796  -0.0791292 ]
   [-0.20706786 -0.51325405 -0.45413423]
   [ 0.49233451  0.18315828 -0.11095257]]

  [[ 0.30043569  0.13640419 -0.07883039]
   [ 0.09435701 -0.06755543 -0.10842759]
   [-0.22471718  0.11327182  0.12290932]]

  [[ 0.85377574  0.54417753  0.2029732 ]
   [-0.3245388  -0.04117646  0.41804892]
   [ 0.45198494  0.05717055  0.64358526]]]


 [[[ 0.27808616 -0.05840755 -0.99811262]
   [ 0.91650122  0.59587646 -0.42878583]
   [ 1.38801038  0.84957308 -0.27346233]]

  [[-0.30557671  0.67243505  1.05331039]
   [-0.75939018  0.08055729  0.8877579 ]
   [-0.99525791 -0.68197203  0.3973839 ]]

  [[-0.46158257  0.79644388  0.22149633]
   [-1.11750543 -0.05984045 -0.88105267]
   [ 1.00280964  0.97050434  0.44936067]]

  [[ 0.03072515  0.42680386 -0.50137824]
   [-0.43645719 -0.27598628 -0.25353488]
   [ 0.73373896 -0.48743752  0.14143114]]]


 [[[-0.29113311 -0.2968657  -0.76124632]
   [-0.41352701 -0.20361485 -0.76195771]
   [-0.37231886 -0.47130078 -0.59065205]]

  [[-0.4317973  -0.30489215 -0.16632286]
   [ 0.19728214  0.07837477  0.30107018]
   [ 0.47553018  0.43354931  0.45248222]]

  [[-0.19242385 -0.02724457  0.59242481]
   [-0.08976278 -0.04668926 -0.17313901]
   [-0.51755637 -0.39758518 -0.17454609]]

  [[ 0.24901141 -0.17936386 -0.91408461]
   [ 0.25167441 -0.33444363  0.00344374]
   [ 0.02630736  0.04460052 -0.24195156]]]]), CudaNdarray([-2.74057388 -1.13451767 -0.69347119 -0.65855223 -1.45420063 -1.3963747
 -2.58478141 -0.86258739 -1.56950152 -2.0154295  -0.83600777 -1.19224346
 -1.30910766 -1.30014694 -1.0975548  -1.19868994 -1.06602192 -1.18646228
 -0.86395139 -1.08066916 -1.09416664 -1.34036589 -0.67637753 -1.17393482
 -1.296646   -1.93042874 -2.02995753 -1.09843004 -0.55103594 -3.11809063
 -2.84745932 -1.39242232 -1.19986606 -0.82428789 -1.02349043 -6.47628355
 -1.57731855 -1.24140286 -1.23123968 -2.36973405 -3.52481961 -1.45581758
 -3.06090808 -0.98896873 -0.66302234 -1.20765138 -0.81468683 -1.02941835
 -2.59137821 -1.0085454  -1.76855326 -1.561041   -2.17170954 -0.9072175
 -1.88578737 -1.28662634 -1.43275952 -0.84804511 -1.40974557 -1.03664601
 -3.44133472 -0.92853475 -1.34622431 -1.69780052]), CudaNdarray([[[[ -1.03899086e+00  -7.07712948e-01  -2.11633012e-01]
   [ -7.01015055e-01  -5.49534857e-01  -4.23155546e-01]
   [ -4.74046022e-01  -6.90073490e-01  -3.20720673e-01]]

  [[ -2.84042004e-02   7.65760913e-02   1.68639973e-01]
   [  1.55218923e-02  -5.14774360e-02   1.02452047e-01]
   [ -1.79808512e-01   1.20908879e-02   1.63017139e-01]]

  [[  3.20427001e-01   1.84102327e-01  -7.90930837e-02]
   [ -9.83949155e-02  -7.94056952e-02   4.98850755e-02]
   [  8.11649710e-02  -3.69171977e-01   1.64390311e-01]]

  ..., 
  [[ -8.31661522e-02   3.43939334e-01  -7.62134641e-02]
   [ -1.26789913e-01   7.70685002e-02   1.37099728e-01]
   [ -2.34002825e-02  -7.41033182e-02  -4.06539366e-02]]

  [[  8.17659050e-02   3.09216175e-02   2.24263132e-01]
   [  1.50205746e-01  -1.83322132e-01   2.37460360e-02]
   [  9.91108567e-02   4.93976139e-02  -2.59389788e-01]]

  [[  9.94211063e-02  -1.39090121e-01   1.03914693e-01]
   [ -3.89624611e-02  -2.44604453e-01   1.40192807e-01]
   [ -1.02255931e-02  -1.08521447e-01  -5.45864552e-02]]]


 [[[  4.21363451e-02   7.60455206e-02   1.19353160e-02]
   [ -1.50640711e-01  -7.61038065e-02  -1.64500862e-01]
   [  6.96105585e-02   3.58057097e-02  -1.05892017e-01]]

  [[ -1.19794691e-02   2.35678688e-01   1.49746716e-01]
   [  2.74288267e-01   2.95506585e-02  -1.46746516e-01]
   [  7.02063292e-02   3.00397605e-01   1.46357521e-01]]

  [[ -3.98736686e-01   2.06390262e-01   2.11049512e-01]
   [ -8.29093456e-01   1.48714751e-01   5.05870223e-01]
   [ -5.65862775e-01  -8.11843053e-02   2.73979813e-01]]

  ..., 
  [[ -4.22204465e-01   1.69449568e-01   1.24200471e-01]
   [ -5.13087332e-01   2.71862149e-01   3.49688709e-01]
   [ -1.83554769e-01  -5.20480871e-02   4.14058179e-01]]

  [[  3.76208633e-01  -6.76626060e-03  -3.06220949e-01]
   [ -4.46010828e-02  -1.21677458e-01  -4.18908074e-02]
   [  6.00888073e-01   1.66827142e-01   7.95492157e-02]]

  [[  1.36160493e-01  -8.85431131e-04   4.21947725e-02]
   [  3.74704786e-02  -1.75046399e-01  -2.46715266e-02]
   [  1.28607646e-01   2.69978374e-01  -2.22416520e-02]]]


 [[[ -1.63706779e-01  -1.04198553e-01   4.06934679e-01]
   [ -2.32984364e-01  -2.72022456e-01  -5.58180586e-02]
   [ -8.14285278e-02  -3.11620295e-01   7.78380409e-02]]

  [[ -2.08281472e-01  -1.94994330e-01   1.93768099e-01]
   [  2.05065727e-01  -1.88912004e-01   1.02051280e-01]
   [  3.07391167e-01   1.94093883e-01   1.26985222e-01]]

  [[  2.89210826e-02   3.37665603e-02  -1.68885067e-01]
   [ -5.79501130e-02  -1.25212729e-01   1.82374328e-01]
   [ -6.30563498e-02  -6.66023344e-02   3.38032961e-01]]

  ..., 
  [[ -2.78496947e-02  -1.38177171e-01   1.40720326e-02]
   [ -7.05079958e-02   1.66841540e-02   1.32828847e-01]
   [ -2.38252133e-01  -9.54170898e-03  -1.29620969e-01]]

  [[ -8.87866020e-02   1.74003541e-01   1.28994912e-01]
   [ -8.15632716e-02   9.21947360e-02  -1.27922624e-01]
   [ -1.75515562e-01  -4.23329696e-02  -8.66991132e-02]]

  [[  8.89702663e-02   2.65070163e-02   1.22281060e-01]
   [  2.14318112e-02   1.01329006e-01   1.04073621e-01]
   [  1.26187846e-01   7.41014481e-02  -4.58548576e-01]]]


 ..., 
 [[[ -1.39322085e-02  -7.48385116e-02   6.04572594e-02]
   [  7.21339732e-02  -1.04897290e-01   1.32871062e-01]
   [ -1.42650649e-01   4.01423126e-02   1.33083910e-01]]

  [[  1.29407048e-01  -1.76004156e-01  -1.76393196e-01]
   [ -4.27057594e-01  -2.73238778e-01  -4.65516970e-02]
   [  4.92012538e-02   1.88883349e-01  -2.40974035e-02]]

  [[  2.82483578e-01  -3.83545682e-02  -5.32374501e-01]
   [  1.31620318e-01   4.44245517e-01  -4.54534031e-02]
   [ -6.72854900e-01   1.17982086e-02  -3.06252902e-03]]

  ..., 
  [[  1.17148787e-01  -7.57174045e-02  -1.62829623e-01]
   [ -7.18301907e-02  -2.06233054e-01  -2.17311889e-01]
   [  1.88488483e-01  -1.97878256e-01  -3.31659973e-01]]

  [[  6.57003224e-02   2.45777845e-01  -5.15913218e-02]
   [ -1.59431592e-01  -1.47671178e-01  -1.94173589e-01]
   [ -1.86218843e-01  -5.02392888e-01  -3.60086113e-01]]

  [[ -3.82547788e-02  -2.11749300e-01  -1.62553191e-01]
   [ -2.23683923e-01  -2.77007937e-01  -3.30271095e-01]
   [ -3.59805077e-01  -1.29774302e-01  -2.24200502e-01]]]


 [[[  9.00591910e-02   1.53719157e-01   1.29912362e-01]
   [ -5.41887999e-01  -1.40945524e-01   1.78245559e-01]
   [ -3.90058637e-01   2.38208249e-01   1.45306677e-01]]

  [[ -3.24758232e-01  -1.03807926e-01   2.88663805e-01]
   [ -9.80183482e-02  -1.49351090e-01  -4.64355834e-02]
   [ -8.06551948e-02  -2.21072212e-01   5.96008636e-02]]

  [[  1.18570644e-02  -2.07448438e-01  -4.14732426e-01]
   [  6.32610396e-02   5.97655308e-03  -1.29465088e-01]
   [ -4.93409038e-02  -3.84661071e-02  -3.48135084e-01]]

  ..., 
  [[ -1.66930556e-01  -5.26171438e-02  -1.01584740e-01]
   [ -4.51719351e-02  -4.13630866e-02  -3.04748062e-02]
   [ -1.03941984e-01  -2.04513341e-01  -2.35877708e-01]]

  [[  6.17120927e-03  -6.78258240e-02   2.99164802e-01]
   [ -3.42159241e-01  -1.02156721e-01  -1.23017870e-01]
   [ -2.23340355e-02  -1.97053552e-01   1.80716872e-01]]

  [[ -5.04926920e-01  -5.51133215e-01  -2.16891497e-01]
   [ -1.67067677e-01  -7.70940706e-02  -1.65254682e-01]
   [  5.47637604e-02   8.38366896e-02   3.49199682e-01]]]


 [[[ -2.00566560e-01  -6.08267859e-02   2.56233215e-01]
   [ -2.05440164e-01   3.46872099e-02  -1.73426680e-02]
   [ -2.32734665e-01  -8.38465095e-02   2.78081506e-01]]

  [[ -5.78814298e-02  -2.83751756e-01  -4.31368828e-01]
   [ -1.08790912e-01  -3.21476273e-02  -5.50257117e-02]
   [ -1.51891857e-01   8.87714326e-02   3.36857200e-01]]

  [[ -5.11330813e-02  -2.88898975e-01  -2.21825927e-01]
   [ -2.15393394e-01  -3.02071840e-01  -2.43661910e-01]
   [ -4.31054048e-02  -1.30863607e-01  -2.44210571e-01]]

  ..., 
  [[ -4.46269572e-01  -2.99920291e-01  -2.03506961e-01]
   [ -2.17233911e-01  -2.26960093e-01  -1.80521339e-01]
   [ -4.70269352e-01  -3.12532425e-01  -2.79511690e-01]]

  [[  2.18881071e-01   2.63184309e-01  -2.04858646e-01]
   [ -1.06189549e-01   1.81126595e-01   1.26284093e-01]
   [ -4.75525707e-01  -7.02133253e-02  -3.45842876e-02]]

  [[ -4.19395655e-01  -2.08264068e-01   6.50537238e-02]
   [ -3.91429096e-01  -3.48257005e-01  -1.41326636e-01]
   [ -1.17312081e-01   2.40765121e-02   2.72505522e-01]]]]), CudaNdarray([ 0.49784726 -2.71426821 -1.11221349 -1.1041913  -1.03609371 -3.04800701
 -0.16594319 -0.03479904 -0.47234794  0.45210433  0.56915796 -0.26683602
  0.07859489 -0.26729497 -0.98864454 -0.10822032  0.33516884  0.06537934
  0.82912201 -1.07308316 -1.50282371 -0.41145244  0.26148129 -0.74645901
  0.89112067  0.20490104 -0.4848544   0.46606058 -1.0468235  -0.63714308
 -2.02621412  1.12329006  0.5200491  -0.40593448 -0.35442084 -0.69448453
 -0.23921628 -0.1935934  -1.32455301 -0.05105822 -0.77319735 -1.08783245
 -0.51363599 -1.1831547   1.16395259  0.53548926  0.0685631   0.10538217]), CudaNdarray([[[[ -5.55648625e-01  -1.79825678e-01  -3.61613005e-01]
   [ -3.55482250e-01   8.51372853e-02   1.08920790e-01]
   [ -2.03540817e-01  -3.66130799e-01  -2.58501291e-01]]

  [[  2.71673519e-02  -9.07710791e-02  -9.26804915e-02]
   [ -1.43091112e-01   9.90352780e-02  -3.21438052e-02]
   [  2.56391056e-03  -2.15093404e-01  -2.71666080e-01]]

  [[ -2.85745054e-01  -2.53985852e-01  -1.43779561e-01]
   [ -1.89220712e-01  -4.57067430e-01  -2.80681461e-01]
   [ -2.18005657e-01  -2.31698230e-01  -1.33097291e-01]]

  ..., 
  [[  1.95007294e-01   5.20254485e-02  -5.75287491e-02]
   [ -1.11263946e-01  -7.18951523e-02   2.05041841e-01]
   [  2.87175179e-01   1.32054985e-01   2.63389111e-01]]

  [[ -3.36218834e-01  -1.06769353e-01  -6.85672522e-01]
   [ -3.97022426e-01  -9.36661102e-03  -3.61389220e-01]
   [  2.45367482e-01   2.15815440e-01  -6.20777346e-02]]

  [[ -9.23185110e-01  -5.76843917e-01   1.17314950e-01]
   [ -4.69182074e-01   3.14978659e-02  -1.13426581e-01]
   [ -4.43677783e-01   8.15381780e-02   2.19053328e-01]]]


 [[[ -7.32762039e-01  -5.15851140e-01  -5.43630481e-01]
   [ -3.93457144e-01   1.55082449e-01  -1.61027566e-01]
   [ -3.76486599e-01   4.75623518e-01  -9.33504552e-02]]

  [[ -1.29457727e-01  -3.79549444e-01  -8.00150558e-02]
   [  4.34240676e-04  -2.54949749e-01   5.27031571e-02]
   [  2.57813781e-01  -1.70749292e-01  -1.76687278e-02]]

  [[  1.67016372e-01   1.20158710e-01   4.85534035e-03]
   [ -1.35218903e-01  -7.44681293e-03  -6.91842288e-02]
   [ -2.59279370e-01  -4.27595258e-01   6.71064481e-02]]

  ..., 
  [[  1.67320609e-01  -2.90186316e-01   7.30859935e-02]
   [  1.17270239e-01  -1.27158880e-01  -2.77034054e-03]
   [  2.04600364e-01  -1.17118977e-01   8.35249797e-02]]

  [[ -3.35401028e-01  -2.67125934e-01  -2.52650708e-01]
   [ -6.80978000e-01  -3.42269927e-01  -5.07875681e-01]
   [ -7.73451865e-01  -2.19997376e-01  -6.53473318e-01]]

  [[ -3.47463638e-01   2.69559950e-01  -3.42725992e-01]
   [ -6.57833755e-01  -8.37404504e-02  -2.46688366e-01]
   [ -6.52560771e-01  -2.26491943e-01  -3.70176256e-01]]]


 [[[ -3.18797588e-01  -4.92443740e-01  -6.24714315e-01]
   [ -1.52522502e-02  -4.83457744e-01  -5.77130973e-01]
   [  2.79248774e-01  -1.31189093e-01  -2.44657531e-01]]

  [[ -3.72677088e-01  -2.06303030e-01  -2.56270654e-02]
   [ -1.94880158e-01  -6.13101661e-01  -6.74544871e-01]
   [ -5.14626922e-03  -2.40905657e-01  -2.96184480e-01]]

  [[  1.44294932e-01   5.49624227e-02   4.96466495e-02]
   [  1.61056442e-03  -1.01255044e-01  -1.84084326e-01]
   [ -2.01997414e-01   7.14274123e-02  -3.36322844e-01]]

  ..., 
  [[ -1.14907198e-01  -1.89924881e-01   7.52249286e-02]
   [ -2.07206875e-01  -4.47041579e-02  -5.60476482e-02]
   [  3.68176936e-03   2.91991308e-02  -1.59765221e-02]]

  [[ -3.28368038e-01  -3.28406155e-01  -8.09243545e-02]
   [  1.07602224e-01  -3.48054320e-01  -3.20792437e-01]
   [ -4.36068267e-01  -2.93477982e-01  -6.80678114e-02]]

  [[  6.44836128e-02  -1.38979301e-01   1.70734048e-01]
   [ -8.25592577e-02  -6.52305305e-01  -9.03024524e-02]
   [ -7.15177834e-01  -2.36048579e-01  -9.93438363e-02]]]


 ..., 
 [[[ -5.74441515e-02  -2.01479761e-05   3.64914209e-01]
   [ -1.20179340e-01  -2.06076000e-02   3.53526771e-01]
   [  4.84761670e-02  -1.22195743e-01  -2.87635505e-01]]

  [[  9.54280570e-02   6.21371418e-02  -1.10822320e-01]
   [  6.61599040e-02  -5.66540301e-01  -6.54143393e-01]
   [ -4.25048470e-01  -3.97795856e-01  -1.98025033e-01]]

  [[ -3.49553376e-02  -2.05245353e-02  -3.19508523e-01]
   [  6.76648095e-02  -1.02825813e-01   8.62115920e-02]
   [  1.72031745e-01  -2.79542357e-01   3.32226530e-02]]

  ..., 
  [[ -2.83571124e-01  -3.86120863e-02  -1.01143934e-01]
   [ -1.17121726e-01  -3.41369808e-01  -1.97162181e-02]
   [ -1.54332444e-01  -8.29130769e-01  -3.63507330e-01]]

  [[  7.55020045e-03  -1.96728647e-01   1.23352945e-01]
   [  1.60791352e-02  -4.00688648e-01  -2.30615109e-01]
   [  3.36848572e-02  -3.52880061e-01  -1.70150161e-01]]

  [[ -8.41762245e-01  -4.68672127e-01  -4.92002100e-01]
   [ -3.25839847e-01   2.50189006e-02  -1.25648424e-01]
   [  2.09391847e-01  -1.88512038e-02  -3.06263715e-01]]]


 [[[ -6.10930383e-01  -7.88463652e-02   2.31257789e-02]
   [ -6.32044077e-01  -3.72007973e-02   2.14581832e-01]
   [ -1.72792822e-02   2.34253228e-01   7.00529873e-01]]

  [[ -3.79397690e-01  -1.84121013e-01  -1.14102766e-01]
   [ -3.86830062e-01  -1.13217428e-01  -1.84172884e-01]
   [ -4.34637666e-01  -5.04779875e-01  -3.54876012e-01]]

  [[ -2.88205981e-01  -2.99837394e-03  -1.09929599e-01]
   [ -4.10349607e-01  -2.09614977e-01  -1.08842507e-01]
   [ -3.54432195e-01  -4.73019272e-01   1.63771957e-02]]

  ..., 
  [[  2.34551474e-01  -2.03053206e-01  -4.90765721e-01]
   [  3.31355453e-01  -1.16921186e-01  -3.58813375e-01]
   [ -6.03953362e-01  -5.66076398e-01  -1.68049440e-01]]

  [[ -3.97382945e-01  -2.11691439e-01  -2.14038100e-02]
   [ -1.35982051e-01  -6.51247725e-02  -2.08420947e-01]
   [  2.09441975e-01   1.81963041e-01   5.11703230e-02]]

  [[ -5.55412710e-01  -1.58026785e-01   6.41783774e-02]
   [ -1.61994115e-01  -2.32920408e-01  -8.03103149e-02]
   [  6.35767728e-02   4.21562716e-02  -1.70794874e-01]]]


 [[[  4.00789320e-01   2.27411151e-01   7.76451686e-03]
   [  1.55687809e-01   1.80896848e-01  -2.00919002e-01]
   [  1.53829113e-01  -9.89933386e-02  -1.18696764e-01]]

  [[ -5.42708874e-01  -6.07862249e-02   6.17021136e-02]
   [ -4.89879906e-01  -3.65410596e-01   5.69286346e-02]
   [ -1.97755307e-01  -6.64011896e-01  -1.62389532e-01]]

  [[ -2.22932771e-02  -1.78043172e-01  -1.84667036e-01]
   [ -1.84764639e-01  -1.50077954e-01  -4.66146648e-01]
   [ -2.75428861e-01   1.26808599e-01  -4.86701965e-01]]

  ..., 
  [[ -1.67878807e-01  -2.43076250e-01  -2.25258723e-01]
   [  1.18252508e-01   1.55508265e-01  -4.16026115e-02]
   [  1.90830737e-01   1.06237851e-01   3.38129640e-01]]

  [[ -1.70554057e-01  -4.82548401e-02  -7.61807486e-02]
   [  1.18868969e-01   1.78441152e-01  -6.30484894e-02]
   [  2.24672869e-01   3.60591292e-01   2.36986890e-01]]

  [[ -1.92939460e-01   1.24149211e-01  -2.29781792e-01]
   [ -1.96496978e-01  -4.17728722e-03   2.77659327e-01]
   [  7.15690106e-02   3.53786737e-01   3.25949788e-01]]]]), CudaNdarray([  1.27055705e+00   8.50887418e-01   8.89142096e-01   7.73467600e-01
  -3.52138281e-02  -9.31092322e-01   1.00548851e+00  -1.20622742e+00
  -8.93839419e-01  -1.32000232e+00  -1.12079298e+00   1.14844131e+00
  -1.64053068e-01  -5.01149833e-01  -1.36425510e-01  -1.37293428e-01
  -9.11656320e-01  -1.89826548e+00   1.11320841e+00  -1.03427899e+00
  -5.03704846e-01  -6.12142324e-01  -5.65057576e-01  -1.83385730e-01
   4.46549058e-02  -4.87145096e-01   1.28062832e+00  -6.26982450e-01
  -1.63078332e+00   3.12236361e-02   6.24971390e-01  -1.69142187e-01
  -1.15813471e-01  -3.72082412e-01  -2.00406820e-01  -1.43870770e-03
   3.26791376e-01  -1.08686164e-01   2.23068029e-01  -1.23560476e+00
  -9.62841436e-02   3.15122992e-01   6.04475856e-01  -7.70970881e-01
   6.31489813e-01  -3.87436181e-01   4.27955955e-01   1.13671340e-01]), CudaNdarray([[[[ 0.20699319  0.2013782   0.26907879]
   [-0.58195883 -0.38540438 -0.07240457]
   [-0.16374162 -0.11952751 -0.23488639]]

  [[-0.31098777 -0.28300887 -0.35616425]
   [-0.34404886 -0.37568954 -0.24432164]
   [-0.592906   -0.8672151  -0.4145757 ]]

  [[-0.54837143 -0.00803814  0.22543061]
   [-0.61656743 -0.0418414   0.11627364]
   [ 0.0073747  -0.11680636 -0.13924092]]

  ..., 
  [[ 0.15914346  0.03732125  0.15304466]
   [-0.25509763 -0.20628117 -0.19913357]
   [ 0.26758206 -0.03504071 -0.14913511]]

  [[ 0.12625043 -0.0114356  -0.04234314]
   [ 0.11181271 -0.00714431 -0.06726231]
   [-0.31914628 -0.09711426 -0.02451522]]

  [[ 0.18885413  0.05213578 -0.22542185]
   [ 0.20163171 -0.04044927 -0.08259725]
   [ 0.14037065 -0.31893805 -0.3056078 ]]]


 [[[ 0.10505183  0.0843349  -0.57331598]
   [ 0.04833136  0.0691833  -0.03750575]
   [ 0.04499397  0.1464811   0.22817394]]

  [[-0.05536383  0.09383938  0.12866049]
   [-0.16909552  0.04706055  0.03530479]
   [-0.23509692 -0.45561871  0.02804477]]

  [[-0.23888488  0.09540261  0.14374751]
   [ 0.1850135   0.17701079  0.08370428]
   [-0.17606618 -0.37336686  0.09134468]]

  ..., 
  [[ 0.02525026  0.1269418  -0.05586118]
   [ 0.02385484 -0.10042107  0.1017136 ]
   [-0.10112617 -0.16565005  0.07036643]]

  [[ 0.04418899  0.134166   -0.36088249]
   [-0.06577702  0.20694712 -0.38826266]
   [-0.3456482   0.33338091  0.19576673]]

  [[-0.6085431  -0.08657744 -0.51388979]
   [-0.12194053 -0.08553903 -0.46814999]
   [-0.47653204 -0.18545027 -0.21915966]]]


 [[[-0.02281508  0.12503664 -0.28227508]
   [-0.17915194 -0.36990798 -0.05005167]
   [-0.02025367 -0.05584679  0.0166137 ]]

  [[-0.33090734 -0.47326595  0.0383277 ]
   [ 0.20293297 -0.28655279 -0.05095611]
   [ 0.09031997 -0.05666732 -0.10507414]]

  [[-0.29664114 -0.53470111  0.10287395]
   [-0.04709946 -0.14990729  0.0778084 ]
   [ 0.35083401  0.07387653 -0.05328261]]

  ..., 
  [[-0.51846009 -0.236835   -0.22659963]
   [-0.50640941 -0.53435594 -0.16856329]
   [-0.04450612 -0.06036286 -0.0104828 ]]

  [[-0.1515477  -0.12912974 -0.56418335]
   [ 0.29304543 -0.10884951  0.0070933 ]
   [ 0.34004366  0.27846581  0.14274275]]

  [[-0.27796367  0.14167489 -0.31374326]
   [-0.16969347 -0.13885014 -0.18226485]
   [-0.27951482 -0.00992526  0.07558949]]]


 ..., 
 [[[-0.23150547 -0.32728028 -0.25769648]
   [-0.17655089 -0.41131529  0.05343656]
   [-0.18227644 -0.17692231  0.00838388]]

  [[ 0.02864032  0.14321266  0.12594509]
   [-0.27837056 -0.05131846  0.10145558]
   [-0.50749558 -0.10084471 -0.03569219]]

  [[-0.03847692 -0.58925426 -0.77645123]
   [ 0.22065689  0.00345068 -0.14500436]
   [ 0.24153152  0.10567209 -0.39263681]]

  ..., 
  [[-0.01037799 -0.01221335  0.04547688]
   [ 0.06419542 -0.01942509  0.20392558]
   [-0.03578002  0.24260777  0.19972987]]

  [[-0.07895266  0.19871186  0.05674917]
   [ 0.06790239 -0.0385462  -0.24463423]
   [ 0.01233307 -0.45919096 -0.24354298]]

  [[ 0.19116873  0.09023892  0.08200169]
   [-0.27167848 -0.07721376 -0.13123474]
   [ 0.2535713   0.14867975 -0.23826264]]]


 [[[ 0.19106571  0.02854091  0.06139765]
   [ 0.30297297  0.14660056 -0.07580548]
   [ 0.21287966 -0.08717956  0.26693073]]

  [[-0.55640596 -0.66656661 -0.66886538]
   [ 0.04251923 -0.4210366   0.19398862]
   [ 0.23728853  0.22951351  0.16600609]]

  [[ 0.25252715 -0.07036147 -0.01103672]
   [-0.01437161 -0.08905008 -0.15794489]
   [ 0.06510416 -0.20819385 -0.23607792]]

  ..., 
  [[-0.11612321  0.197984   -0.06423724]
   [ 0.04049082  0.20648503  0.23354927]
   [ 0.06491268 -0.11354759 -0.0466683 ]]

  [[ 0.0721854  -0.1971247  -0.02225072]
   [-0.32230574 -0.32425833  0.42623046]
   [-0.75231457 -0.25579238  0.28591195]]

  [[ 0.15298374  0.04932999  0.34639147]
   [ 0.17260227  0.03551251  0.05287162]
   [ 0.15045966 -0.17068471 -0.40324107]]]


 [[[-0.15075611  0.11353582  0.07292648]
   [-0.34331554 -0.06689552 -0.1733899 ]
   [-0.15645373 -0.31936792 -0.2078416 ]]

  [[-0.08005071 -0.13809991 -0.12880091]
   [ 0.06236064 -0.02503674 -0.43043342]
   [-0.31823993 -0.16109647 -0.5239132 ]]

  [[ 0.05150248 -0.12936625 -0.25815621]
   [ 0.24772477 -0.01911427 -0.35052732]
   [ 0.21586443  0.14792195  0.15761676]]

  ..., 
  [[ 0.01544535 -0.31117681  0.21648997]
   [-0.46108755 -0.34196696 -0.13508414]
   [-0.5066644  -0.05267448 -0.3300153 ]]

  [[-0.11529198 -0.00449779  0.21895851]
   [-0.09709139  0.04266135  0.15187022]
   [ 0.10297898  0.19023524  0.01521488]]

  [[ 0.08442704  0.33765978  0.47518468]
   [-0.08595871  0.1405237   0.03329588]
   [-0.49468771 -0.16239651  0.13497087]]]]), CudaNdarray([-0.85461867 -1.86372256 -1.83810806 -1.30129552 -2.25499082 -1.58926201
 -1.27909851  0.11986187 -0.01122112 -0.73687857 -1.83246195 -1.48389208
 -1.09200466 -1.08404684 -1.23793888 -1.06812596 -0.54343522 -2.68596625
 -1.90270388 -1.18021798 -3.15566039 -1.96465921 -0.09206514 -0.23439957
 -0.6171484  -0.03147016  0.64855653 -1.8581574  -0.5476042  -1.42260003
 -1.43420613 -2.69175601 -0.99124217 -0.68188941 -1.45070386  0.73159212
 -0.036773   -1.93029594 -2.2104187  -2.21118212 -1.13737571 -2.31913924
 -1.85402608 -0.16982625 -0.01069263  1.64269364 -0.73218721 -0.82166547]), CudaNdarray([[-0.06848672 -0.33572665 -0.07107727 ..., -0.17395231 -0.09427123
  -0.15778545]
 [-0.1053133  -0.12989189 -0.11146113 ..., -0.05436127 -0.04165371
  -0.05645037]
 [-0.07607694  0.1937665  -0.08325466 ..., -0.0128378  -0.06449713
  -0.07773026]
 ..., 
 [-0.08130579  0.08930684  0.0105402  ..., -0.12867884 -0.25652361
  -0.07186937]
 [ 0.07619429 -0.01234148  0.02239468 ..., -0.11565392 -0.07549141
  -0.1699619 ]
 [-0.0517144  -0.08033436 -0.1534216  ..., -0.16262934  0.04459566
  -0.01990528]]), CudaNdarray([ 0.52357852 -0.01783111  0.07731287 -0.00364406 -0.35613233 -0.32693422
 -0.12796393 -0.29243365 -0.31510758 -0.06928634  0.2329455  -0.11234906
 -0.35195634 -0.57962024 -0.23654303 -0.16352095 -0.17839967 -0.34639308
 -0.39088351 -0.07987365 -0.34626684 -0.01925754 -0.47046909  0.22863658
 -0.36188659 -0.24834223 -0.40385228 -0.46205595 -0.58263499 -0.30537841
  0.38482466 -0.15126875 -0.46604154 -0.3130644   0.02149743 -0.34848282
 -0.24013472 -0.40802357 -0.57288998 -0.14348722 -0.19219846 -0.2847088
 -0.41119453 -0.38899589 -0.53053039 -0.06887289  0.05662401 -0.2764014
 -0.4875572  -0.09845036 -0.34658757 -0.2734898  -0.36827528 -0.49329543
 -0.18831451 -0.43290284 -0.24036311 -0.3569319   0.26829717 -0.52199906
 -0.10858479 -0.36605829 -0.29521289 -0.41880953 -0.41492102 -0.33575931
 -0.48623294  0.3217217  -0.27030534 -0.32895422 -0.52415931  0.22506455
 -0.28238952 -0.5864594   0.52458072  0.10082451 -0.21772686 -0.19034253
  0.2589508   0.24633992 -0.35676482 -0.30276668 -0.13991085 -0.21367197
 -0.44213939 -0.31238797 -0.32260439 -0.28380531 -0.34743235 -0.39402589
  0.24449416 -0.34010997  0.39104825 -0.35936487 -0.28533751 -0.40035331
 -0.29501492 -0.38677913 -0.44412914  0.01422633 -0.3453556  -0.50576997
 -0.22333752 -0.16369551 -0.27767888 -0.18318087 -0.0877958  -0.13896893
 -0.13851462 -0.09876841 -0.32290983 -0.48627183 -0.00338196 -0.28516126
 -0.38968039 -0.49598476 -0.32379904 -0.14818592 -0.4638887   0.29184014
 -0.03173776 -0.43803906 -0.60893506 -0.26404229  0.06498861  0.13461599
 -0.00493341  0.39552459  0.17613403 -0.15922701  0.12015506 -0.11280567
 -0.44072449 -0.05592389  0.58828735 -0.38194701 -0.17959666 -0.29529426
 -0.39595687  0.02977487 -0.21576361 -0.07933643 -0.33692628 -0.41386136
 -0.50428945 -0.19546616 -0.35819575 -0.40301138  0.24154288 -0.31251034
 -0.28872401 -0.3779012  -0.39568758 -0.46067911 -0.45391703  0.38111824
 -0.27443603 -0.29580015  0.34471974 -0.38461193 -0.46627942 -0.37328067
  0.27390683 -0.25727731 -0.24887413 -0.19804481 -0.11404207  0.20817073
 -0.61621475 -0.34672672 -0.15061474 -0.2041375  -0.02946394 -0.09461129
 -0.2400448  -0.25069812 -0.2658585   0.39937869 -0.5702796  -0.27101833
 -0.0985413  -0.02901251 -0.33886659 -0.43808007 -0.25267333 -0.29406348
 -0.0107666  -0.30063695 -0.23241754 -0.04143662 -0.30632222 -0.44307354
 -0.32479161 -0.19375615 -0.08727518 -0.31011057 -0.41108403 -0.23616123
 -0.3806456  -0.37781402 -0.31396595 -0.03323183 -0.2826466  -0.55961293
  0.09723458  0.4324038  -0.4447602  -0.12822288 -0.33649722 -0.46298087
 -0.42106128  0.712493    0.22792031 -0.2211436  -0.2855351   0.13757761
 -0.2352581  -0.02834443 -0.57085526 -0.31747121 -0.27859983 -0.41983455
 -0.20311739  0.04826026 -0.23682971 -0.53673124 -0.47183874 -0.15817536
 -0.34489369 -0.3755281  -0.33744821 -0.03757681 -0.19875269 -0.32473496
 -0.19288358  0.24819569 -0.38563603 -0.45698711 -0.0822138  -0.50499064
 -0.31096229 -0.35365707 -0.06800243 -0.32865894 -0.22331034 -0.391332
  0.07080496  0.23248808  0.15689689 -0.39302257 -0.26074806  0.13585259
 -0.44453838 -0.30344915 -0.36679229 -0.13879441 -0.46136782 -0.20684598
  0.73663926 -0.64427888 -0.23848794  0.18872266 -0.26647669 -0.34564805
 -0.53769571 -0.28196073  0.1393282  -0.27473903 -0.38637713 -0.40029821
 -0.24811952  0.2693747  -0.40213484  0.0591583   0.27540344  0.17569894
 -0.22156411 -0.11748885  0.37776309 -0.32430854 -0.61923176 -0.40115964
  0.01748041 -0.36342731 -0.36302677  0.12329946 -0.47874576  0.14094758
 -0.51723963 -0.21139294 -0.08989806 -0.43624386 -0.19295749  0.35104665
 -0.47666857 -0.33413064  0.34239367 -0.34059665  0.76573247  0.3221353
 -0.34732318  0.23286167 -0.34926352 -0.14106604 -0.46457344  0.15495199
 -0.10631211 -0.3132982  -0.25006017 -0.54519612  0.25929168 -0.38716224
 -0.32241088 -0.07562296  0.5857175  -0.49681512 -0.58091128 -0.02452225
  0.34577787 -0.18901156 -0.43460339 -0.2374524  -0.32651827 -0.25215653
 -0.38206542 -0.14136426 -0.48309159 -0.40168726 -0.37955669 -0.13195479
 -0.24653247 -0.21106654 -0.26149884 -0.29968277 -0.14129052 -0.14729905
 -0.32032147 -0.21844411  0.19615367  0.39451849 -0.00794706 -0.22201607
 -0.28843975 -0.31325033 -0.27143949 -0.56251854 -0.38388371 -0.4103083
 -0.37241739 -0.34709114 -0.06099851 -0.41499519 -0.4108997   0.59748715
 -0.40587428 -0.18558121  0.0438692  -0.28604761 -0.32117033 -0.45882159
 -0.52975065 -0.39017385 -0.56362212  0.0820787   0.15889055 -0.44029233
 -0.31319505 -0.13850315  0.46378759 -0.43248558 -0.47536048 -0.20070918
 -0.22525129 -0.4666813  -0.18412945  0.30412441  0.32067299 -0.47067124
 -0.07593413 -0.32684657  0.06977993  0.21698521 -0.448668   -0.32665497
 -0.32957852  0.39889029  0.07412888 -0.30364683 -0.22588806 -0.20183824
 -0.4677639  -0.07294455 -0.17599098  0.10982081 -0.38466233 -0.14775789
 -0.03250871  0.48380649 -0.39447561  0.18687671  0.85304582 -0.30317995
 -0.15089183 -0.04337175 -0.25354233 -0.45101556  0.36320588  0.76642936
 -0.14543885 -0.37699264 -0.23424518  0.30583501  0.06192807 -0.40903655
 -0.29673663 -0.21148628  0.46016479  0.19370078 -0.35756475 -0.36428457
 -0.30110162 -0.30343154 -0.14009333 -0.30904722 -0.45453531 -0.24182095
 -0.43088859 -0.17942481 -0.48664209 -0.23568381 -0.1634589  -0.15664105
 -0.33569863 -0.35428596 -0.22757947 -0.29998881 -0.16339374 -0.31850693
 -0.40565157 -0.24922869 -0.2513068  -0.19725107 -0.58533931  0.10144134
 -0.39964196 -0.17208143 -0.48142383 -0.24599028 -0.09064478 -0.1574381
  0.09930992 -0.42003098 -0.12762159 -0.00608147  0.00643839 -0.50780487
  1.01192486 -0.01556108  0.0581543  -0.25012633 -0.4601917   0.22153559
 -0.24238002 -0.17479649 -0.34798312  0.08447235 -0.38560548 -0.31243512
 -0.58055836 -0.24480104 -0.40828323 -0.2001816  -0.28481776 -0.32080147
 -0.5565514   0.0268389  -0.1883125  -0.36878756  0.00168926 -0.27392891
 -0.2517961  -0.16945283 -0.26607943 -0.06422154 -0.07502812  0.01182062
 -0.21326819 -0.40349117 -0.47873637 -0.29913801 -0.18927744 -0.30986848
 -0.18622714 -0.0474378  -0.37858048  0.16422316 -0.02008451 -0.21538948
 -0.4574129   0.00652995 -0.1200077  -0.20264925 -0.15487912 -0.13973069
 -0.02296904 -0.27035806 -0.42095849 -0.3561379  -0.19328526 -0.0071193
 -0.53268999 -0.38141188]), CudaNdarray([[ 0.02255613 -0.02403588]
 [-0.10956398 -0.02643624]
 [ 0.01040248  0.05602583]
 ..., 
 [-0.09703961  0.09959773]
 [ 0.0451781  -0.08670858]
 [ 0.01042011 -0.07449926]]), CudaNdarray([-0.43991706  0.4402543 ])]))

In [39]:
e_p = []
p = []
for z in range(250,300):
    
    image, prob, mask, gold, rhoana = gp.Util.read_section('/home/d/data/cylinderNEW',z)
    
    error_patches, patches = gp.Patch.patchify_maxoverlap(image, prob, mask, rhoana, gold, sample_rate=1, clamp_result=False)
    
    e_p.append(error_patches)
    p.append(patches)    

Loading z00000250.png
Loading z00000251.png
Loading z00000252.png
Loading z00000253.png
Loading z00000254.png


KeyboardInterrupt: 

In [34]:
# for z in range(0,1):
e_p = []
p = []
image, prob, gold, rhoana, bb = gp.Legacy.read_dojo_data()

for z in range(0,10):

    error_patches, patches = gp.Patch.patchify_maxoverlap(image[z], prob[z], np.zeros((image[0].shape[0], image[0].shape[1])), rhoana[z], gold[z], sample_rate=1, clamp_result=False)
    
    e_p.append(error_patches)
    p.append(patches)

a


In [29]:
len(e_p[0]), len(p[0])

(40, 348)

In [40]:
# cconvert to FP format with target
import neuroproof
import neuroproof.FocusedProofreading as fp
graph = fp.Graph('/home/d/FP/dojo_test_NEW/graph.json')


In [52]:
g_n = graph.find_close_bodies(5,0,0.)
zn = []
for n in g_n:
    zn.append(n[1])

In [53]:
np.max(zn)

0.71764704585075378

In [87]:
graphs = []
for z in range(10):
    
    g = fp.Graph('/home/d/FP/dojoNEW/graph_'+str(z)+'.json')
    graphs.append(g)

In [88]:
fp_y_test_proba = []
fp_y_test = []
gt_y_test = []
for z in range(10):
    
    cur_e_p = e_p[z]
    cur_p = p[z]
    
    g = graphs[z]
    
    for pa in cur_e_p:
#         print pa['l'], pa['n']
        
        label1 = pa['l']
        label2 = pa['n']

        graph_neighbors = sorted(g.find_close_bodies(label1,0,0.))

        pred = [ne[1] for ne in graph_neighbors if ne[0] == label2]
        
        fp_y_test.append(np.round(pred))
        fp_y_test_proba.append(pred)
        gt_y_test.append(1)
        
    for pa in cur_p:
#         print pa['l'], pa['n']
        
        label1 = pa['l']
        label2 = pa['n']

        graph_neighbors = sorted(g.find_close_bodies(label1,0,0.))

        pred = [ne[1] for ne in graph_neighbors if ne[0] == label2]
        
        fp_y_test.append(np.round(pred))
        fp_y_test_proba.append(pred)
        gt_y_test.append(0)
        
        

    



In [30]:
from sklearn.metrics import classification_report, accuracy_score, roc_curve, auc, precision_recall_fscore_support, f1_score, precision_recall_curve, average_precision_score, zero_one_loss


In [90]:
print 'Precision/Recall:'
print classification_report(np.array(gt_y_test), np.array(fp_y_test))

Precision/Recall:
             precision    recall  f1-score   support

          0       0.94      0.69      0.80      3488
          1       0.14      0.51      0.21       332

avg / total       0.87      0.68      0.75      3820



In [91]:
acc_score = accuracy_score(np.array(gt_y_test), np.array(fp_y_test))
print 'Accuracy Score:', acc_score

Accuracy Score: 0.677486910995


3820

In [92]:
gp_y_test_proba = []
gp_y_test = []
gt_y_test = []
for z in range(10):
    
    cur_e_p = e_p[z]
    cur_p = p[z]
    
    for pa in cur_e_p:
#         print pa['l'], pa['n']
        
        label1 = pa['l']
        label2 = pa['n']

        pred = gp.Patch.test_and_unify([pa], cnn)
        
        gp_y_test.append(np.round(pred))
        gp_y_test_proba.append(pred)
        gt_y_test.append(1)
        
    for pa in cur_p:
#         print pa['l'], pa['n']
        
        label1 = pa['l']
        label2 = pa['n']

        pred = gp.Patch.test_and_unify([pa], cnn)        
        
        gp_y_test.append(np.round(pred))
        gp_y_test_proba.append(pred)
        gt_y_test.append(0)

NameError: name 'cnn' is not defined

In [36]:
print classification_report(np.array(gt_y_test), np.array(gp_y_test))

             precision    recall  f1-score   support

          0       1.00      0.92      0.96      3488
          1       0.54      0.95      0.69       332

avg / total       0.96      0.92      0.93      3820



In [38]:
acc_score = accuracy_score(np.array(gt_y_test), np.array(gp_y_test))
print 'Accuracy Score:', acc_score

Accuracy Score: 0.924607329843
